### ISSUE TITLE
device is not initialized error

### ISSUE THREAD

**Issue by td344526** [luxonis/depthai-experiments#13]
Hi,

With depthai version "0.2.0.1+f91a36fac86a0f4383e863e04cb651869a1603ac" I'm getting device is not initialized error on raspberry pi. Atteched is the error log.

XLink initialized.
Sending internal device firmware
Failed to boot the device: 1.2-ma2480, err code 3
depthai: Error initializing xlink
2020-11-24 16:54:34,380 - depthai_utils - INFO - Creating DepthAI pipeline...
device is not initialized

**Comment by alex-luxonis** [comment]
Hi @td344526,

Indeed, we had a bug in that version, that was fixed in the next merged PR:
https://github.com/luxonis/depthai/pull/240 -> https://github.com/luxonis/depthai-python/pull/58 -> https://github.com/luxonis/depthai-core/pull/16 -> https://github.com/luxonis/XLink/pull/2

I see that several of our apps on `depthai-experiments` repo are using this problematic version. Thanks for the issue report, we'll update them to a newer depthai version.

In the meantime, could you check if the apps you're interested in are working with the latest version from here:
https://github.com/luxonis/depthai/blob/main/requirements.txt -- stable version
https://github.com/luxonis/depthai/blob/develop/requirements.txt -- latest/development version
