### ISSUE TITLE
Can you share the IR model?

### ISSUE THREAD

**Issue by huytuong010101** [luxonis/depthai-experiments#130]
About gen2-mask-detection
Your OpenVINO version isn't compatible with my code
So can you share the IR model(.yml, .bin) which i can covert it to Blob model myself?
Many thank <3

**Comment by Erol444** [comment]
Hello @huytuong010101,
I believe the mask detection model is [sbd mask](https://github.com/sbdcv/sbd_mask/tree/master/model), you have the model in the onnx format on their github. You can convert onnx -> IR with the [model optimizer](https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_Deep_Learning_Model_Optimizer_DevGuide.html).

And you can set the OpenVino model version with `pipeline.setOpenVINOVersion(version=dai.OpenVINO.Version.VERSION_2020_1)`, since the models in the `gen2-mask-detection` were compiled with OpenVino **2020.1**.

Thanks, Erik

**Comment by huytuong010101** [comment]
Thank you for your reply

**Comment by Erol444** [comment]
No problem, happy to help :)

**Comment by huytuong010101** [comment]
Hey, do i need add any paramerter on command when convert from oonx to IR?
```python3 mo.py --input_model <INPUT_MODEL>.onnx```
