### ISSUE TITLE
Depth information in deep learning model

### ISSUE THREAD

**Issue by NQHuy1905** [luxonis/depthai-experiments#516]
I have read document about use depth information, but i still get some questions

For example i want to do object detection, so the input of model will only from rgb camera or input will be both rgb camera and stereo depth

And why output of rgb and disparity of demo in this link below is different

https://docs.luxonis.com/projects/api/en/latest/samples/SpatialDetection/spatial_tiny_yolo/#rgb-tinyyolo-with-spatial-data

**Comment by Erol444** [comment]
Hi @NQHuy1905 ,
You can do that as well, just note that majority of the model architectures out there are RGB only, that's why most of our demos are with such models as well.
There were a few projects that did object detection on RGBD, I believe only this one is public:
https://www.youtube.com/watch?v=BGaOO0MzBv0

Could you elaborate on the last question, how do you mean they are different?

**Comment by NQHuy1905** [comment]
@Erol444 hi, from the tutorial link i send above, there is demo video and they have output like this
![Screenshot 2024-01-22 235408](https://github.com/luxonis/depthai-experiments/assets/87300546/7a2f78c1-33a9-4526-9899-77086657cfdc)
My question is why the rectangle of object in rgb and disparity is different.
From my understand, it just align result coordinate from rgb to disparity right?

And what if i want to detect object in low illumination condition, what camera node should i use

**Comment by Erol444** [comment]
Hi @NQHuy1905 , 
Oh I see, I believe the old video wasn't updated with RGB-depth alignment, but in general they are aligned, see example here: 
https://docs.luxonis.com/projects/api/en/latest/samples/StereoDepth/rgb_depth_aligned/#rgb-depth-alignment
Thoughts?
