### ISSUE TITLE
Gen2 OCR Demo

### ISSUE THREAD

**Issue by dhruvsheth-ai** [luxonis/depthai-experiments#78]
After the depthai lib update, the Demo works well, however the text recognition part after the detection inferences a bit too fast for the human eye to spot.
Perhaps a possible fix could be letting the text spotting model make inferences, but, the text recognition model output the recognised text on the different frame after a specific duration. 
(last_text_recognised.time - current_text_recognised.time) = 1second

**Comment by themarpe** [comment]
@dhruvsheth-ai seems like a good way to improve this. 
I think that the root cause of flickering is that vstack appends whenever a new frame arrives as well as the text.
Maybe it be better to store all results first (of both transformed images and decoded text) and then display together once only.

If you'd like to give this a try in some form or another feel free to do so and open a PR. Will be glad to take a look:)

**Comment by dhruvsheth-ai** [comment]
Sure! Will open a PR this week, with the mechanism you mentioned as well, will test and post the results

**Comment by dhruvsheth-ai** [comment]
So, I tried using threading function to delay a specific part and not affect the rest, but that's not effective.
I'm trying to use another mechanism which you suggested

**Comment by dhruvsheth-ai** [comment]
To open a PR later, with an effective threading solution

**Comment by magallardo** [comment]
Is anyway this demo can be updated to run the inference for a provided image file? 

Thanks

**Comment by dhruvsheth-ai** [comment]
You can add argument inputs for that

**Comment by magallardo** [comment]
@dhruvsheth-ai I am looking for an example where the pipeline input is an image instead of the camera.  For ocr I would like to feed one image at a time.  All the examples use camera stream as input to the pipeline and I would like to see some simple example where the input is just an image in the file system. 

Thanks

**Comment by Luxonis-Brandon** [comment]
I think we can add this as an alternate input.  

@VanDavv - thoughts?
